#!/bin/zsh
params=()
output="./a.out"
TIMEFMT='total   %*E
user    %U
sys     %S
mem     %M MB'
NEEDTIME='HELLO'
while [[ $# -ne 0 ]]; do
	case $1 in
		-o)
			params+=("$1")
			shift
			output="$1"
			;;
		end)
            print -P '%F{3}%BWarning:%b%f'" 'end'" "is deprecated, use '--params' instead"
            shift
            break
            ;;
        --params)
			shift
			break
			;;
        --notime)
            unset NEEDTIME
            shift
            continue
            ;;
	esac
	params+=("$1")
	shift
done
if gcc "${params[@]}"; then
    if [ -z "$NEEDTIME" ]; then
        "$(realpath "$output")" $@
    else
	    time "$(realpath "$output")" $@
    fi
fi
