#!/bin/zsh
params=()
output="./a.out"
TIMEFMT='total   %*E
user    %U
sys     %S
mem     %M MB'
while [[ $# -ne 0 ]]; do
	case $1 in
		-o)
			params+=("$1")
			shift
			output="$1"
			;;
        -)
            STDIN='y'
            ;;
		end|--params)
            print -P '%F{3}%BWarning:%b%f'" 'end' and '--params'" "are deprecated, use '--' instead"
            shift
            break
            ;;
        --)
			shift
			break
			;;
        --notime)
            TIMEFMT=''
            shift
            continue
            ;;
	esac
	params+=("$1")
	shift
done
compile_program() {
    if [ -z $STDIN ]; then
        g++ "${params[@]}" || return 1
    else
        FILE="${params[2]}"
        params[2]='-'
        tail -n +2 < "$FILE" | g++ -x c++ "${params[@]}" || return 1
    fi
}
compile_program && time "$(realpath "$output")" $@

